### ISSUE TITLE
Add: Slash command that tells the time

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#10]
Add an application command (or slash command) that tells the user the current time. The slash command takes no parameters, and the reply should only be seen by the user, and not be shown in the channel's chat.

Refer [here](https://github.com/bwmarrin/discordgo/blob/master/examples/slash_commands/main.go) for an example of how to implement slash commands.

**Comment by salman0ansari** [comment]
i would like to work on this one.

**Comment by z404** [comment]
Thank you for your interest! I've assigned you
