### ISSUE TITLE
Add: Command to join a voice channel and play a buzzer sound

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#12]
When a user sends the `!buzzer` command, the bot should be able to join the voice channel that the user is currently in, and play a buzzer sound. The bot should leave the voice channel after the buzzer sound is done playing. Appropriate error handling for when user is not in a voice channel should be done.

Refer to [this](https://github.com/bwmarrin/discordgo/blob/master/examples/airhorn/main.go) example as a reference.

**Comment by salman0ansari** [comment]
assign me

**Comment by z404** [comment]
Assigned!
