### ISSUE TITLE
Add: Command Logging system

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#16]
The bot should take a channelID given by the developer (specified in constants or `.env` file), and for every command it receives, sends a message to that channel with information on who sent the command, which server the command was sent on, and what command was used.

A reference is given below:

![image](https://user-images.githubusercontent.com/49672329/194714131-a2e59628-669b-474f-a97c-9b5358166815.png)

**Comment by sculley** [comment]
Hello, please assign this issue to me. I would like to work on this.

**Comment by z404** [comment]
Please finish other issues that you've been assigned to. I'd be happy to assign this issue to you after you've finished your other issues if this one is still available.

**Comment by sculley** [comment]
Sure not a problem, thanks!

**Comment by z404** [comment]
Hi @sculley are you still interested in working on this issue?
