### ISSUE TITLE
Add: A weather command

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#20]
Create a command `!weather <location_name>`, to which the bot replies with certain weather information related to the location provided. For obtaining the weather information, use the [OpenWeatherMap GO API](https://github.com/briandowns/openweathermap).

Refer to [this](https://pkg.go.dev/github.com/briandowns/openweathermap#readme-examples) for examples on how to make a request to this API. Be sure *not* to commit your API key while committing your code.

**Comment by JusteenR** [comment]
Hi @z404 ! I am interested on working on this issue and was wondering if I could be assigned it?

**Comment by z404** [comment]
Absolutely! Looking forward to your contribution :D
