### ISSUE TITLE
Fix: Prefix issue

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#22]
Currently, the bot is set with the prefix of `!`. This is set in the constants, and is subject to change. The bot checks every message to see if it starts with the prefix. If it does, it checks what command was executed. The bug here is that on the switch-case of the command checking, the `!` prefix is hardcoded. 
```go
...
switch strings.ToLower(strings.Split(m.Content, " ")[0]) {
    // if the command is !greet
    case "!greet":
        s.ChannelMessageSend(m.ChannelID, randomGreeting(s, m))
    ...
...
```

If the prefix in the constants is changed, the bot breaks, and none of the commands are accessible by users. Change the switch-case conditions to make commands flexible to changes in prefix.

**Comment by techsnap** [comment]
Hi, I would like to work on this.

**Comment by z404** [comment]
Sure! Assigned.

**Comment by ankan792** [comment]
hey can i work on this issue?

**Comment by z404** [comment]
hi @ankan792, I'm sorry, but this issue doesn't need multiple people working on it, and I've already assigned @techsnap to this issue. There are other open issues that you can try though. Thank you for showing interest!
