### ISSUE TITLE
Add: Anonymous whisper command

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#25]
Create a slash command `/whisper`, which takes 2 arguments, the destination user, and a message. The bot should send a direct message to the destination user, without telling the destination user who initiated the command. The reply to the slash command must be visible only to the sender.

For example:
1. Wilford Warfstache#0256 uses the slash command as `/whisper @_MarkFriend An anonymous person says hi!`
2. MarkFriend receives a direct message from GollyBot, that says "You have a new anonymous whisper: "An anonymous person says hi!"
3. GollyBot replies to the slash command with "The whisper was delivered!" that is only visible to Wilford

**Comment by ryuusama09** [comment]
hi , I would like to work on this issue .

**Comment by z404** [comment]
Looking forward to your contribution! Assigned!

**Comment by z404** [comment]
Hi @ryuusama09 it has been a while since I've heard from you. If you're facing any difficulties, do discuss it here so we may be able to help out!

**Comment by z404** [comment]
Hi @ryuusama09 as I haven't heard from you for a very long time, I will have to unassign you from this issue. If you still want to take up the issue, please drop a message here!

**Comment by ryuusama09** [comment]
hi @z404  sorry for such a late response. Ive been stuck with a few pre commitments of mine , so you can go ahead and unassign this issue . Sorry for holding up 
 thank you

**Comment by SeethaLakshmiGanesan** [comment]
@z404  can work on this issue. Please assign it to me.

**Comment by z404** [comment]
Sure! Assigned!
