### ISSUE TITLE
Add: Function that searches for results on Youtube

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#31]
Create a function `searchYT` that takes a search string as a parameter, and returns the first search result it finds that matches the search string. The function needs to return the link to the video and the title of the video. Appropriate response needs to be given when errors are faced (Ex: "No search results were found!")

Important: Create the function in a *different* file, called `music.go`. Import this file into `main.go` and create a simple command for the that calls this function (as a means of testing this function) (call the command `!searchyt <search_string>`)

**Comment by techsnap** [comment]
Hey, I would like to work on this issue.

**Comment by z404** [comment]
Sure, Assigned!

**Comment by z404** [comment]
Hi @techsnap  it has been a while since I've heard from you. If you're facing any difficulties, do discuss it here so we may be able to help out!

**Comment by techsnap** [comment]
Hi, I am facing difficulty with YouTube API. I was trying [this code example](https://developers.google.com/youtube/v3/code_samples/go#search_by_keyword) but it gives an error at this part of code:

```go
// Make the API call to YouTube.
call := service.Search.List("id,snippet").
        Q(*query).
        MaxResults(*maxResults)
response, err := call.Do()
handleError(err, "")
```

First, the Search.List throws an error saying it requires argument of type []string instead of type string and after fixing that, `handleError` throws an error.
So, I looked for another go libraries for making youtube requests but the ones I found ([like this one](https://github.com/lithdew/youtube)) are outdated

**Comment by z404** [comment]
The first code example you linked is extremely old, with the last modification being done in 2018. Also, using the YouTube API will add so many dependencies to the project that we don't want. Instead, make a HTTP request directly to the endpoint they specified in the docs. You'll still use the same developer key, but in a more direct way

Here's what I could get working for me:

```go
package main

import (
	"flag"
	"net/http"
	"log"
	"io/ioutil"
)

var (
	query      = flag.String("query", "Google", "Search term")
	maxResults = flag.Int64("max-results", 25, "Max YouTube results")
)

const developerKey = "[YOUR DEVELOPER KEY]"

func main() {
	flag.Parse()

	// Make the API call to YouTube.
	resp, err := http.Get("https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q="+ *query +"&key="+developerKey)
	if err != nil {
		log.Fatalf("Error making search API call: %v", err)
	}

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}
	//Convert the body to type string
	sb := string(body)
	log.Printf(sb)
}
```
I forgot to set maxResults in the query string, but I think you get the idea

**Comment by techsnap** [comment]
Thanks for simplifying things. Will soon create a PR.
