### ISSUE TITLE
Add: Set of functions that act as database functions

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#34]
Create a file `db.go` that has the following functions:

 - `isExistDB` : Checks if the file `db.json` exists, returns boolean value true or false
 - `createDB` : Creates a new file `db.json`. If the file exists, overwrite the file and create a new one
 - `writeToDB` : Takes a Map variable (where the key and the value are both strings), and writes into database if exists. Returns true if write is successful
 - `readFromDB` : Takes a string key as parameter, and returns the string associated with it, else returns appropriate response if not found

Write a main function to test the functioning of these methods.

**Comment by ArshErgon** [comment]
okay I got it, but what if the `db.json` has some data, do still need to overwrite that file?

**Comment by z404** [comment]
If `createDB` is called, it overwrites the file even if data is present. If `writeToDB` is called, then it only appends and does not overwrite. 

I'll assign the issue to you :D

**Comment by ArshErgon** [comment]
ahhh, I can't figure out how should I save the data in the json file like?
I mean, if I saved it like `{'key':'value'}` how will I be printing it out / filtering it out by the key?
```
func writeToDB(key, value string) bool  {
	data := map[string]string{
		key:value,
	};
	jsonS, jsonString := json.Marshal(data);
	if jsonString != nil {
		return false;
	}
	fmt.Println(string(jsonS));
	f, err := os.OpenFile("db.json", os.O_APPEND|os.O_WRONLY, 0644);
	if err != nil {
		panic(err)
	}
	if _, err = f.WriteString(string(jsonS)); err != nil {
		panic(err)
	}
	f.WriteString("\n");

	return true;
}
```

**Comment by z404** [comment]
Okay, so the `db.json` file needs to be maintained as a storage for all key value pairs right? Let's say we use writeToDB to write the following key value pair:
```go
writeToDB("key1", "value1")
```

The status of the file would be:
```json
{
    "key1": "value1"
}
```

The next time writeToDB is called again, with a different key and value, the new keypair will be appended to the file in json format.
```go
writeToDB("key2", "value2")
```
Status of `db.json`:
```json
{
    "key1": "value1",
    "key2": "value2"
}
```

This can be achieved by reading the file `db.json` as a regular string, and parsed into a Map variable ([this](https://appdividend.com/2022/03/15/how-to-convert-json-to-map-in-golang/) article specifies how to achieve this). The map variable can then be converted to string to write into a file ([this](https://stackoverflow.com/questions/48149969/converting-map-to-string-in-go) article helps with that)

(Note: the formatting in `db.json` doesn't matter, it could be written as one straight line.)

**Comment by z404** [comment]
Hi @ArshErgon, do let me know if you need any more clarification!

**Comment by ArshErgon** [comment]
Hi @z404 no i will do it, if I failed I ask you about it

**Comment by ArshErgon** [comment]
@z404 hey, theres no way that the json file can append the data, we can only getting data at runtime, means we can retrieve the data only once, if we run the program again with different key and values as parameters, the previous one will get deleted and the new key will take its place.

**Comment by z404** [comment]
Sure, create a PR with whatever you have so far, we'll try and work with that for now
