### ISSUE TITLE
Add: Command that accesses WolframAlpha API

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#35]
Add a command `!math <math problem>`. When the user executes this command, the bot must make a request to the WolframAlpha API using [this](https://pkg.go.dev/github.com/Krognol/go-wolfram#section-readme) package. The reply contains a set of "pods". Sort through these pods and return those that are useful for answering the question.

You may take a look at the website [here](https://www.wolframalpha.com/input/?i=go+programming+language)

**Comment by ankan792** [comment]
@z404 Please assign me this issue!

**Comment by ankan792** [comment]
@z404 this somehow doesn't seem to work. Am I doing something wrong? The app id is functioning properly.
`var mathProb = strings.SplitN(m.Content, " ", 2)[1]
			c := &wolfram.Client{AppID: "app-id"}

			//Get a result without additional parameters
			res, err := c.GetQueryResult(mathProb, nil)

			if err != nil {
				panic(err)
			}
			s.ChannelMessageSend(m.ChannelID, res)

			// Iterate through the pods and subpods
			// and print out their title attributes
			for i := range res.Pods {
				s.ChannelMessageSend(m.ChannelID, res.Pods[i].Title)

				for j := range res.Pods[i].SubPods {
					s.ChannelMessageSend(m.ChannelID, res.Pods[i].SubPods[j].Title)
				}
			}`

**Comment by ankan792** [comment]
@z404 this somehow doesn't seem to work. Am I doing something wrong? The app id is functioning properly.

`                var mathProb = strings.SplitN(m.Content, " ", 2)[1]
                c := &wolfram.Client{AppID: "app-id"}

		//Get a result without additional parameters
		res, err := c.GetQueryResult(mathProb, nil)

		if err != nil {
			panic(err)
		}
		s.ChannelMessageSend(m.ChannelID, res)

		// Iterate through the pods and subpods
		// and print out their title attributes
		for i := range res.Pods {
			s.ChannelMessageSend(m.ChannelID, res.Pods[i].Title)

			for j := range res.Pods[i].SubPods {
				s.ChannelMessageSend(m.ChannelID, res.Pods[i].SubPods[j].Title)
			}
		}`

**Comment by ankan792** [comment]
@z404 this somehow doesn't seem to work. Am I doing something wrong? The app id is functioning properly.
`var mathProb = strings.SplitN(m.Content, " ", 2)[1]
c := &wolfram.Client{AppID: "app-id"}

		//Get a result without additional parameters
		res, err := c.GetQueryResult(mathProb, nil)

		if err != nil {
			panic(err)
		}
		s.ChannelMessageSend(m.ChannelID, res)

		// Iterate through the pods and subpods
		// and print out their title attributes
		for i := range res.Pods {
			s.ChannelMessageSend(m.ChannelID, res.Pods[i].Title)

			for j := range res.Pods[i].SubPods {
				s.ChannelMessageSend(m.ChannelID, res.Pods[i].SubPods[j].Title)
			}
		}`

**Comment by ankan792** [comment]
@z404 this somehow doesn't seem to work. Am I doing something wrong? The app id is functioning properly.

                var mathProb = strings.SplitN(m.Content, " ", 2)[1]
 
                c := &wolfram.Client{AppID: "app-id"}
                res, err := c.GetQueryResult(mathProb, nil)

		if err != nil {
			panic(err)
		}
		s.ChannelMessageSend(m.ChannelID, res)

		// Iterate through the pods and subpods
		// and print out their title attributes
		for i := range res.Pods {
			s.ChannelMessageSend(m.ChannelID, res.Pods[i].Title)

			for j := range res.Pods[i].SubPods {
				s.ChannelMessageSend(m.ChannelID, res.Pods[i].SubPods[j].Title)
			}
		}

**Comment by z404** [comment]
I'm assigning you to this issue!

**Comment by z404** [comment]
I'm afk at the moment, I will test the API on my end and put up a post here when I have an update!

**Comment by ankan792** [comment]
@z404 sure!

**Comment by z404** [comment]
As is seen with most outdated APIs, this one is very broken.

![image](https://user-images.githubusercontent.com/49672329/195879220-cb279fd7-ac3e-41fc-89a5-1339ed7bb0dd.png)

I'm trying to get this to work directly using the API endpoint, as I did here: #31. I'll add a comment once that works.

**Comment by ankan792** [comment]
@z404 I got the exact same output with this. Definitely broken. However I found another work around with the GetSpokentAnswerQuery function and this seems to work just fine. 
```golang
                        res, err := c.GetSpokentAnswerQuery(mathProb, wolfram.Metric, 1000)
			if err != nil {
				panic(err)
			}
			s.ChannelMessageSend(m.ChannelID, res)

![image](https://user-images.githubusercontent.com/34034274/195894103-16656ab7-e631-4730-b239-a4b5d3c76dc1.png)

**Comment by z404** [comment]
Nice! This works perfectly, though the output seems a little odd (as it is meant to be spoken, not shown as text). We can work with this for now, and if need be, correct it later. Proceed with using this work-around. Good job :D

**Comment by ankan792** [comment]
@z404 yeah the output is a bit weird but def works! Since the search applies for generic queries as well, should we name the call the command !math or something else maybe?

**Comment by z404** [comment]
If you have a better name in mind, feel free to change it!

**Comment by ankan792** [comment]
@z404 alright thanks!
