### ISSUE TITLE
Fix: Bug in reminder command

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#37]
When a user enters the command as given below, the bot tries to parse the word "to" as an integer, and fails. (syntax of command is `!remindme <seconds> <message>`)
```
!remindme to drink water and stay hydrated
```
The bot does not respond when parsing to integer fails. Fix the command such that if parsing the number of seconds fails, then the bot replies to the user saying that it could not parse seconds, and that the syntax of the command is `!remindme <seconds> <message>`

**Comment by ankan792** [comment]
Hey I'll try to work on this issue

**Comment by z404** [comment]
Sure! Assigned.

**Comment by ankan792** [comment]
@z404 Is it alright to directly print the error message and then tell the user to use correct syntax?

**Comment by z404** [comment]
Anything works! you can directly print the error, or you can say something like "Something went wrong, try again! the syntax is ..."

**Comment by ankan792** [comment]
Cool!

**Comment by z404** [comment]
You're right! Feel free to open an issue on this repository by following the same structure I do on my issues :D
