### ISSUE TITLE
Add: Dockerfile to build discord bot in a docker container

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#38]
For ease of deployment of the bot on any platform, a Dockerfile is required. This way, an image can be run on any platform, irrespective of how the platform is configured.

Create a Dockerfile that can create an image that runs GollyBot when run.

For more information on how Dockerfiles work, check [this](https://docs.docker.com/language/golang/build-images/#create-a-dockerfile-for-the-application) out

**Comment by ari0211** [comment]
Hi!
Can i try to work on this?

**Comment by z404** [comment]
Sure! Thanks for showing interest :D

**Comment by z404** [comment]
Closed by #51
