### ISSUE TITLE
Add: Welcome message for newcomers

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#44]
Add an event listener which listens for new member joins. When a new member joins, the bot should send a message welcoming them with a message (tagging the user) and an [image](https://thumbs.dreamstime.com/b/welcome-banner-shiny-colorful-confetti-vector-paper-illustration-welcome-banner-colorful-confetti-100006906.jpg)

**Comment by RohitShah1706** [comment]
@z404 
Please assign me this one

**Comment by z404** [comment]
Sure, assigned!

**Comment by SeethaLakshmiGanesan** [comment]
@z404 I would like to work on this issue. Please assign it to me.

**Comment by z404** [comment]
Assigned!

**Comment by SeethaLakshmiGanesan** [comment]
Hi @z404 
I have a doubt. If the server has multiple channels, should we send the welcome message to all of them or just a specific channel - for example, the general channel

**Comment by z404** [comment]
One channel is enough I think. Sending a message on the general channel should do the job

**Comment by SeethaLakshmiGanesan** [comment]
Sure, thanks
