### ISSUE TITLE
Add: ServerInfo Command

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#45]
Add a command `!serverinfo`. This command should provide the following information:
 - Owner of the server
 - Number of category channels in the server
 - Number of text channels in the server
 - Number of voice channels in the server
 - Number of members in the server
 - Number of roles in the server

Send this information to the user in the form of an [Embed](https://pkg.go.dev/github.com/bwmarrin/discordgo#MessageEmbed)

**Comment by moazfarrukh** [comment]
@z404 can you assign this to me?

**Comment by z404** [comment]
Sure! Assigned.

**Comment by moazfarrukh** [comment]
@z404 there seem to be some errors in the code of the bot in the getenv function.
the function is defined inside the main function
while its being called for variables above it in the global scope
![image](https://user-images.githubusercontent.com/21291203/195132401-1a5b4a80-4bbf-47fb-81bc-0c922a592034.png)
![image](https://user-images.githubusercontent.com/21291203/195132638-a9cf335d-b830-4324-b10a-ffa0ad67088e.png)

**Comment by moazfarrukh** [comment]
i made a fix by declaring it outside the main function. this seems to work for me
![image](https://user-images.githubusercontent.com/21291203/195134200-a041bb46-808b-417f-bb9e-d650801c570c.png)

**Comment by moazfarrukh** [comment]
@z404 can you tell me what do you mean by category channels?

**Comment by z404** [comment]
Category channels are the dropdowns that can contain voice or text channels in them. An example is given below:

![image](https://user-images.githubusercontent.com/49672329/195141497-eb537327-8210-48b8-9d9f-4a25e8a639b7.png)

If you're not sure on how to implement the counting of category channels, you can omit it.

**Comment by moazfarrukh** [comment]
> Category channels are the dropdowns that can contain voice or text channels in them. An example is given below:
> 
> ![image](https://user-images.githubusercontent.com/49672329/195141497-eb537327-8210-48b8-9d9f-4a25e8a639b7.png)
> 
> If you're not sure on how to implement the counting of category channels, you can omit it.


oh i see i understand, i can implement that thanks.

**Comment by moazfarrukh** [comment]
@z404 im done with it. have created the pull request : )
