### ISSUE TITLE
Add: Rock Paper Scissors command

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#46]
Add a command `!playrps <choice>`. The bot should choose from rock, paper or scissors randomly, and compare to what the user chose, and decide the winner accordingly. It should reply to the user with information on what the bot chose, and who the winner was.

Add error handling such that if the choice entered by the user is invalid, the bot should reply with a message telling the user the syntax of the command, and the choices they have.

**Comment by ankan792** [comment]
I would like to tackle this issue!

**Comment by z404** [comment]
Sure, assigned!
