### ISSUE TITLE
Fix: Breaking change commited into bot

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#47]
The newest merge caused issues that stop the code from compiling. Fix the code so that the bot may run without errors.

**Comment by ankan792** [comment]
I have the correct code. I will handle it.

**Comment by z404** [comment]
Oh okay, create a PR with just the fix, and I'll take a look. Thanks @ankan792 and @moazfarrukh for notifying me of the breaking changes :D

**Comment by ankan792** [comment]
@z404 review the code and see if it works.
