### ISSUE TITLE
Add: Bot initialization

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#5]
Write the main function of the bot. The main function should do the following:
- Create a new Discord session using the provided bot token.
- Register a function as callback for MessageCreate events.
- Open a websocket connection to Discord and begin listening.
- Wait until CTRL-C or other term signal is received.
- Close the websocket gracefully.

When the bot is running, it must print `The bot is now online!`
Refer to [this](https://medium.com/this-code/building-a-golang-discord-bot-part-1-setup-fbaf73ae878f) article (be sure _not_ to implement more than what was specified in this issue!)

**Comment by Theflashiscool2** [comment]
I got it
