### ISSUE TITLE
Improve: Logging system

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#53]
Currently, the logging system logs every command that is sent to the bot using the prefix. The logging system does not log any slash commands used. Log the slash commands as shown below:

![image](https://user-images.githubusercontent.com/49672329/195182706-dae1cc17-a97b-483e-bc45-5f16294466ad.png)

**Comment by SeethaLakshmiGanesan** [comment]
@z404 I can work on this issue. Please assign it to me.

**Comment by z404** [comment]
Assigned!

**Comment by SeethaLakshmiGanesan** [comment]
Hi @z404, added log for slash command, but not pushed the changes yet.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/77732328/195652343-618dfff2-145e-433b-bcf7-81a79e64dd87.png">

For the commands with bot prefix, should we add some prefix in the log like [BotPrefix] ?

**Comment by z404** [comment]
Sure! It may come in handy later
