### ISSUE TITLE
Add: EventListener that listens for users leaving server

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#59]
Similar to #44, except this time, the event listener listens for when a user leaves a server, and sends a message wishing them goodbye.

**Comment by rudychung** [comment]
Hi, I'd like to work on this issue, could you assign it to me?

**Comment by z404** [comment]
Sure! Assigned!

**Comment by rudychung** [comment]
Is it ok if I follow the same structure as https://github.com/ACM-VIT/golly-bot/pull/58 for creating my message, or would that be considered plagiarism?

**Comment by z404** [comment]
As the task is similar, the functions are bound to be similar. Its alright if the same structure is followed.
