### ISSUE TITLE
Add: env file

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#7]
Add a `.env` file to the repository, with settings like the bot's token, the bot's prefix, and any other settings you see fit. Make sure that the `.env` file is present in the `.gitignore` file so it doesn't accidentally get committed. Add a sample `.env.sample` file with the same fields as the `.env` but without the values so other users know the structure of the file. 

Read the file (along with error handling) in the `init` function of `main.go`

**Comment by nkilm** [comment]
I would like to work on this issue, please assign me.

**Comment by z404** [comment]
Thank you for your interest, looking forward to your contribution! @nkilm

**Comment by z404** [comment]
Hi @nkilm, it's been a day since I've heard back from you, let me know if you need any assistance in implementing this issue.

**Comment by nkilm** [comment]
I'll get to it asap! Little busy as exams are approaching.
