### ISSUE TITLE
Modify: Remove voice functions from main.go

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#70]
Create a new file `voice.go` that contains the following functions:
 - `playSound`
 - `loadSound`

These functions need to be removed from `main.go`. The bot should still run normally when the bot is run with the command `go run main.go voice.go`. Also create a new function `loadPresetDCAFiles` that takes no parameters. This function should perform the same task that this snippet of code does:
```go
err = loadSound("airhorn.dca")
	if err != nil {
		fmt.Println("Error loading sound: ", err)
		return
	}
```

This snippet of code is present in the main function of `main.go` and should be removed.

Future functions in `voice.go` would include streaming a YouTube video's audio to the voice channel etc.

**Comment by mintbomb27** [comment]
Hey! I'd like to work on this.

**Comment by z404** [comment]
Sure! Thanks for showing interest! Assigned :D
