### ISSUE TITLE
Fix: nickchange command

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#73]
The nickname change command `!nickchange` has a few issues:
 - When a person's nickname has been changed successfully, the message that the bot replies with is: "the nick of 352836433746198531 has been changed". Fix this so the userID is replaced with the user's username (Discord username and hash)
 - When changing a persons username, if a nickname of more than one word is provided, the nickname is not changed properly. Fix this such that the nickname is changed entirely.

Example of error:
![image](https://user-images.githubusercontent.com/49672329/196004821-f9e7ede3-8130-4992-9dea-500cea340086.png)

![image](https://user-images.githubusercontent.com/49672329/196004829-cce9940a-f48a-4d44-91ef-a9d370658096.png)

The nickname should have been set as `multi word nickname` but was instead set as `multi`

**Comment by ankan792** [comment]
I'll try to fix it.

**Comment by z404** [comment]
Alright, assigned!
