### ISSUE TITLE
Refactoring repository

### ISSUE THREAD

**Issue by sankalpmukim** [ACM-VIT/golly-bot#75]
So I was setting up my repository and there is several minor code quality issues all over the repository.

- The formatting of db.go file

- Exported functions need to start from a capital letter
- Commenting main() in non main packages (db)
- Capitalized error strings
- Unused fmt.Sprint calls / unnecessary calls
- Redundant return nothing statements at the end of functions

Fell free to add things in your mind

**Comment by sankalpmukim** [comment]
I'd love to take this up as a quick issue

**Comment by z404** [comment]
Thanks for raising this issue, I'll assign this issue to you

**Comment by z404** [comment]
I'd like to also add that the way that environment variables are initialised also seem a little odd, though I may be wrong.  

The environment variables in `main.go` are first initialised as blank, and then assigned thier values. Assigning them directly to thier value might reduce the risk of bugs that lead to blank variables.

A naming system for the variables is also required, as there seem to be no such system for environment variables in the code

**Comment by sankalpmukim** [comment]
For the environment variables, it seems to be done like this to accommodate for global environment variables. To solve this issue there is three options:
1. Make the env variables local to main and pass them to each function as parameters
2. Call os.GetEnv everywhere needed instead of using local/global variables (should not have too big of a performance impact)
3. Separate loading env variables from a separate file and make it easy to refactor in the future by separating this concern.

option 1 and 2 are simple to implement but have severe refactoring cost.
option 3 is going to be very smooth (my favorite)!

**Comment by ankan792** [comment]
@sankalpmukim Great job raising these issues! I had similar concerns regarding the code quality. About the env variables, you are correct I made that change to accommodate for the global variables for the time being.
