### ISSUE TITLE
Add: Greeting command

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#9]
Add a greeting command for when someone says "Hi golly!" in the chat, or uses the `!greet` command. The bot should reply with one of three or more greetings, chosen randomly by the bot.

**Comment by sculley** [comment]
Hello, please assign me this issue. I would like to work on it.

**Comment by z404** [comment]
Thank you for your interest! Assigned!

**Comment by z404** [comment]
Closed by #17
